-- Database name:
-- TreatDB

-- Document your create tables pSQL here
--
-- CREATE TABLE treat (
-- 	id SERIAL PRIMARY KEY,
-- 	name VARCHAR(200),
-- 	description VARCHAR(500),
-- 	pic VARCHAR(500)
-- );
